import { IMAGES } from "../assets";

export const scheduleClassesData = [
  {
    title: "App Development",
    location: "Online",
    teacherName: "Ava Calvar",
    teacherImg: IMAGES.teacher_avatar,
    studentName: "Alex Jhons",
    studentImg: IMAGES.student_avatar,
    time: "10:00am - 11:00am",
    days: "Mon - Thu",
    bgColor: "bg-customCard1Color",
  },
  {
    title: "App Development",
    location: "Online",
    teacherName: "Ava Calvar",
    teacherImg: IMAGES.teacher_avatar,
    studentName: "Alex Jhons",
    studentImg: IMAGES.student_avatar,
    time: "10:00am - 11:00am",
    days: "Mon - Thu",
    bgColor: "bg-customCard2Color",
  },
  {
    title: "App Development",
    location: "Online",
    teacherName: "Ava Calvar",
    teacherImg: IMAGES.teacher_avatar,
    studentName: "Alex Jhons",
    studentImg: IMAGES.student_avatar,
    time: "10:00am - 11:00am",
    days: "Mon - Thu",
    bgColor: "bg-customCard3Color",
  },
  {
    title: "App Development",
    location: "Online",
    teacherName: "Ava Calvar",
    teacherImg: IMAGES.teacher_avatar,
    studentName: "Alex Jhons",
    studentImg: IMAGES.student_avatar,
    time: "10:00am - 11:00am",
    days: "Mon - Thu",
    bgColor: "bg-customCard4Color",
  },
  {
    title: "App Development",
    location: "Online",
    teacherName: "Ava Calvar",
    teacherImg: IMAGES.teacher_avatar,
    studentName: "Alex Jhons",
    studentImg: IMAGES.student_avatar,
    time: "10:00am - 11:00am",
    days: "Mon - Thu",
    bgColor: "bg-customCard5Color",
  },
  {
    title: "App Development",
    location: "Online",
    teacherName: "Ava Calvar",
    teacherImg: IMAGES.teacher_avatar,
    studentName: "Alex Jhons",
    studentImg: IMAGES.student_avatar,
    time: "10:00am - 11:00am",
    days: "Mon - Thu",
    bgColor: "bg-customCard6Color",
  },
  {
    title: "App Development",
    location: "Online",
    teacherName: "Ava Calvar",
    teacherImg: IMAGES.teacher_avatar,
    studentName: "Alex Jhons",
    studentImg: IMAGES.student_avatar,
    time: "10:00am - 11:00am",
    days: "Mon - Thu",
    bgColor: "bg-customCard7Color",
  },
];
