export const studentDetails = [
  {
    id: 1,
    name: "John Doe1",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 2,
    name: "John Doe2",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 3,
    name: "John Doe3",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 4,
    name: "John Doe4",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 5,
    name: "John Doe5",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 6,
    name: "John Doe6",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 7,
    name: "John7",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 8,
    name: "John8 ",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 9,
    name: "John 9",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 10,
    name: "John 10",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 11,
    name: "John 11",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 12,
    name: "John 12",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 13,
    name: "John 13",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
  {
    id: 14,
    name: "John 14",
    email: "johndoe@student.rosewood.com",
    phoneNo: "+1 234 56789",
    checked: false,
  },
];
