export const teacherDetails = [
  {
    id: 1,
    name: "John Doe1",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 2,
    name: "John Doe2",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 3,
    name: "John Doe3",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 4,
    name: "John Doe4",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 5,
    name: "John Doe5",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 6,
    name: "John Doe6",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 7,
    name: "John Doe7",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 8,
    name: "John Doe8 ",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 9,
    name: "John Doe9",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 10,
    name: "John Doe10",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 11,
    name: "John Doe11",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 12,
    name: "John Doe12",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 13,
    name: "John Doe13",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 14,
    name: "John Doe14",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 15,
    name: "John Doe15",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 16,
    name: "John Doe16",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 17,
    name: "John Doe17",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 18,
    name: "John Doe18",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 19,
    name: "John Doe19",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
  {
    id: 20,
    name: "John Doe20",
    email: "john@rosewood.com",
    assignedClasses: "7",
    checked: false,
  },
];
